export const DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID!;
export const WORKSPACES_ID = process.env.NEXT_PUBLIC_APPWIRTE_WORKSPACE_ID!;
export const MEMBERS_ID = process.env.NEXT_PUBLIC_APPWIRTE_MEMBERS_ID!;
export const PROJECTS_ID = process.env.NEXT_PUBLIC_APPWIRTE_PROJECTS_ID!;
export const IMAGE_BUCKET_ID =
  process.env.NEXT_PUBLIC_APPWIRTE_IMAGE_BUCKET_ID!;
